# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B5gFieaBgUyv3VqJEg136h_chjZ0YNkl
"""

!pip install streamlit

import streamlit as st
import types
import tensorflow as tf
from tensorflow import keras

@st.cache(hash_funcs={types.FunctionType: lambda _: None})
def load_model():
    model = keras.models.load_model('model_fashion_mnist.hdf5')
    return model

# Call the function
loaded_model = load_model()

st.write("""
#Fashion MNSIT Detection System"""
)
file=st.file_uploader("Choose plant photo from computer",type=["jpg","png"])
A

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(64,64)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['Alpinia Galanga (Rasna)','Amaranthus Viridis (Arive-Dantu)',
                 'Artocarpus Heterophyllus (Jackfruit)',
                 'Azadirachta Indica (Neem)','Basella Alba (Basale)',
                 'Brassica Juncea (Indian Mustard)','Carissa Carandas (Karanda)',
                 'Citrus Limon (Lemon)','Ficus Auriculata (Roxburgh fig)',
                 'Ficus Religiosa (Peepal Tree)','Hibiscus Rosa-sinensis',
                 'Jasminum (Jasmine)','Mangifera Indica (Mango)',
                 'Mentha (Mint)','Moringa Oleifera (Drumstick)',
                 'Muntingia Calabura (Jamaica Cherry-Gasagase)',
                 'Murraya Koenigii (Curry)', 'Nerium Oleander (Oleander)',
                 'Nyctanthes Arbor-tristis (Parijata)','Ocimum Tenuiflorum (Tulsi)',
                 'Piper Betle (Betel)','Plectranthus Amboinicus (Mexican Mint)',
                 'Pongamia Pinnata (Indian Beech)','Psidium Guajava (Guava)',
                 'Punica Granatum (Pomegranate)','Santalum Album (Sandalwood)',
                 'Syzygium Cumini (Jamun)','Syzygium Jambos (Rose Apple)',
                 'Tabernaemontana Divaricata (Crape Jasmine)',
                 'Trigonella Foenum-graecum (Fenugreek)']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)